import {createRequire} from 'node:module';import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
const base=process.env.CPRP_QA_BASE||'http://localhost:8789';
const secret=process.env.CPRP_QA_SECRET_FILE?JSON.parse(fs.readFileSync(process.env.CPRP_QA_SECRET_FILE,'utf8')).CPRP_PROVISIONING_KEY:process.env.CPRP_QA_PROVISIONING_SECRET||fs.readFileSync('/tmp/cprp-local-admin-secret','utf8');
const out=process.env.CPRP_QA_OUT||'/tmp/cprp-browser-qa';fs.mkdirSync(out,{recursive:true});
const checks=[];const browser=await chromium.launch({headless:true,...(process.env.CPRP_CHROMIUM?{executablePath:process.env.CPRP_CHROMIUM,args:['--no-sandbox','--disable-gpu','--use-gl=angle','--use-angle=swiftshader']}:{} )});
async function device(){const context=await browser.newContext();const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});return {context,page};}
async function call(page,path,data){return page.evaluate(async({path,data})=>{const r=await fetch('/api/cprp'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,body:await r.json()};},{path,data});}
async function accept(page,url){await page.goto(url);await page.locator('#accept-invite').click();await page.waitForURL('**/program/staff/',{timeout:20000});await page.locator('#staff-content').waitFor({state:'visible'});}
const stamp=crypto.randomBytes(6).toString('hex');let secondProgram,program,member1,member2,root,hr,other,person1,person2,connector;
try{
 const health=await (await fetch(base+'/api/cprp/health')).json();assert.equal(health.ok,true);if(process.env.CPRP_EXPECTED_SHA)assert.equal(health.release,process.env.CPRP_EXPECTED_SHA);
 root=await device();const payload=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+300,nonce:crypto.randomBytes(24).toString('base64url')})).toString('base64');const proof=payload+'.'+crypto.createHmac('sha256',secret).update(payload).digest('base64url');
 const bootstrap=await fetch(base+'/api/cprp/bootstrap',{method:'POST',headers:{'X-CPRP-Provisioning-Proof':proof}});assert.equal(bootstrap.status,200);const invitation=await bootstrap.json();await accept(root.page,invitation.url);checks.push('real WebAuthn operator registration');
 const spec={slug:'qa-'+stamp,client_id:'QA_CLIENT',partner_id:'QA_PARTNER',market:'KG',name:'Тестовая программа · '+stamp,client_name:'Тестовый поставщик',partner_name:'Тестовый партнёр',product:'Тестовый абонемент',status:'active',currency:'KGS',terms_ref:'/program/guide/',privacy_ref:'/program/guide/',schedule_ref:'QA-'+stamp,attribution_days:365,membership_bps:3000,treatment_bps:1000,benefits:'Изолированная проверка. Не является предложением услуг.',support:'Тестовая команда'};
 let r=await call(root.page,'/staff/programs',spec);assert.equal(r.status,200,JSON.stringify(r));program=r.body.id;
 async function member(device,passport,name){await device.page.goto(base+'/program/join/?slug='+spec.slug);await device.page.locator('input[name=first_name]').fill(name);await device.page.locator('input[name=last_name]').fill('Проверка');await device.page.locator('input[name=passport]').fill(passport);await device.page.locator('input[name=phone]').fill('+996000000001');await device.page.locator('input[name=consent]').check();await device.page.locator('#registration button').click();await device.page.waitForURL('**/program/member/',{timeout:20000});await device.page.locator('#member-content').waitFor({state:'visible'});return (await call(device.page,'/me')).body.members[0].id;}
 person1=await device();member1=await member(person1,'QA-A001-'+stamp,'Тест Один');checks.push('four-field registration and WebAuthn session');
 person2=await device();member2=await member(person2,'QA-A002-'+stamp,'Тест Два');assert.notEqual(member1,member2);checks.push('shared family phone does not merge people');
 await person1.page.locator('#logout').click();await person1.page.locator('#login').waitFor({state:'visible'});r=await call(person1.page,'/me');assert.equal(r.status,401);await person1.page.locator('#login').click();await person1.page.locator('#member-content').waitFor({state:'visible'});assert.equal((await call(person1.page,'/me')).body.members[0].id,member1);checks.push('logout invalidation and passkey re-login');
 r=await call(person1.page,'/staff/dashboard?program_id='+program);assert.equal(r.status,403);checks.push('participant cannot read HR inventory');
 r=await call(root.page,'/staff/invite',{program_id:program,label:'Тестовый HR',role:'hr'});hr=await device();await accept(hr.page,r.body.url);
 for(const id of [member1,member2]){r=await call(hr.page,'/staff/review',{member_id:id,decision:'verified'});assert.equal(r.status,200);}
 r=await call(hr.page,'/staff/dashboard?program_id='+program);assert.equal(r.body.counters.available,0);assert.equal(r.body.counters.waiting,2);checks.push('HR approves eligibility at zero stock');
 await person1.page.reload();await person1.page.locator('#member-content').waitFor({state:'visible'});const txt=await person1.page.locator('#member-content').innerText();assert.match(txt,/Оформление абонемента ещё не завершено/);assert.doesNotMatch(txt,/Абонементы закончились|Квота|Доступно|На проверке.*2/);await person1.page.screenshot({path:out+'/member-desktop.png',fullPage:true});await person1.page.setViewportSize({width:390,height:844});await person1.page.screenshot({path:out+'/member-mobile.png',fullPage:true});assert.equal(await person1.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);checks.push('truthful participant waiting state without partner balance; mobile overflow');
 r=await call(root.page,'/staff/fund',{program_id:program,quantity:1,amount_minor:10000,eligible_minor:10000,payment_ref:'QA-first-'+stamp,kind:'paid'});assert.equal(r.status,200);
 const results=await hr.page.evaluate(async ids=>Promise.all(ids.map(id=>fetch('/api/cprp/staff/issue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({member_id:id,request_id:crypto.randomUUID()})}).then(r=>r.json()))),[member1,member2]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(results.filter(x=>x.code==='inventory_empty').length,1);checks.push('concurrent last-unit allocation cannot oversell');
 const winner=results[0].ok?member1:member2,loser=winner===member1?member2:member1;
 r=await call(hr.page,'/staff/issue',{member_id:winner,request_id:'retry-'+stamp});assert.equal(r.body.ok,true);r=await call(hr.page,'/staff/dashboard?program_id='+program);assert.equal(r.body.counters.issued,1);checks.push('duplicate issuance is idempotent');
 r=await call(root.page,'/staff/fund',{program_id:program,quantity:99,amount_minor:990000,eligible_minor:990000,payment_ref:'QA-topup-'+stamp,kind:'paid'});assert.equal(r.status,200);r=await call(root.page,'/staff/fund',{program_id:program,quantity:99,amount_minor:990000,eligible_minor:990000,payment_ref:'QA-topup-'+stamp,kind:'paid'});assert.equal(r.status,200);r=await call(hr.page,'/staff/issue',{member_id:loser,request_id:'after-topup-'+stamp});assert.equal(r.body.ok,true);r=await call(hr.page,'/staff/dashboard?program_id='+program);assert.equal(r.body.counters.purchased,100);assert.equal(r.body.counters.issued,2);assert.equal(r.body.counters.available,98);checks.push('100-unit purchase, top-up and funding replay preserve balance');
 const p2=await call(root.page,'/staff/programs',{...spec,slug:'qa-other-'+stamp,partner_id:'QA_OTHER'});secondProgram=p2.body.id;r=await call(hr.page,'/staff/dashboard?program_id='+p2.body.id);assert.equal(r.status,403);checks.push('HR cross-program isolation');
 r=await call(hr.page,'/staff/twenty',{action:'configure',api_key:'SYNTHETIC_UNAUTHORIZED_KEY_000'});assert.equal(r.status,403);const noAdmin=await fetch(base+'/api/cprp/bootstrap/twenty',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:'SYNTHETIC_UNAUTHORIZED_KEY_000'})});assert.equal(noAdmin.status,403);checks.push('CRM credential configuration rejects HR and unauthenticated callers');
 r=await call(root.page,'/staff/invite',{program_id:program,label:'Тестовый координатор',role:'coordinator'});other=await device();await accept(other.page,r.body.url);r=await call(other.page,'/staff/passport',{member_id:member1});assert.equal(r.status,403);r=await call(hr.page,'/staff/passport',{member_id:member1});assert.equal(r.status,200);assert.equal(r.body.passport,'QA-A001-'+stamp);checks.push('passport disclosure restricted to HR with audit');
 r=await call(root.page,'/staff/connector',{program_id:program});assert.equal(r.status,200);connector=r.body;
 async function event(data){const x=await fetch(base+'/api/cprp/connector/events',{method:'POST',headers:{Authorization:'Bearer '+connector.key,'Content-Type':'application/json'},body:JSON.stringify(data)});return {status:x.status,body:await x.json()};}
 const common={member_id:member1,patient_ref:'QA-PATIENT-'+stamp,occurred_at:new Date().toISOString()};r=await event({...common,event_id:'link',kind:'patient_link'});assert.equal(r.status,200);
 r=await event({...common,event_id:'payment',kind:'treatment_payment',payment_ref:'QA-treatment-'+stamp,amount_minor:10000,eligible_minor:10000,currency:'KGS',evidence_ref:'QA-evidence'});assert.equal(r.status,200,JSON.stringify(r));
 const finance=(await call(root.page,'/staff/finance?program_id='+program)).body;assert.equal(finance.totals.fee_minor,301000);const original=finance.ledger.find(x=>x.kind==='treatment');assert.equal(original.evidence_ref,'QA-evidence');assert.equal(original.source_event_ref,connector.id+':payment');checks.push('financial record retains source-event and payment-evidence references');
 r=await call(root.page,'/staff/finance?program_id='+program+'&before='+original.cursor);assert.equal(r.status,200);assert.equal(r.body.ledger.some(x=>x.id===original.id),false);assert.equal(r.body.ledger.length,2);await root.page.reload();await root.page.locator('#staff-content').waitFor({state:'visible'});await root.page.locator('#program-select').selectOption(program);await root.page.locator('summary').filter({hasText:'Twenty и сверка'}).click();await root.page.locator('[data-action=finance]').click();await root.page.locator('#finance-ledger').getByText('QA-evidence',{exact:true}).waitFor();await root.page.setViewportSize({width:390,height:844});assert.equal(await root.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await root.page.screenshot({path:out+'/finance-mobile.png',fullPage:true});checks.push('operator finance detail renders payment evidence and supports older-record cursor');
 r=await event({...common,event_id:'refund',kind:'refund',payment_ref:'QA-refund-'+stamp,amount_minor:2500,eligible_minor:2500,currency:'KGS',evidence_ref:'QA-refund',reverses:original.id});assert.equal(r.status,200);r=await call(root.page,'/staff/finance?program_id='+program);assert.equal(r.body.totals.fee_minor,300750);checks.push('client handoff/link, treatment fee, partial refund and non-overlap with bulk membership');
 const handoff=await fetch(base+'/api/cprp/connector/handoff',{headers:{Authorization:'Bearer '+connector.key}});const hh=await handoff.json();assert.equal(hh.items.length,2);assert.doesNotMatch(JSON.stringify(hh),/passport|QA-A00/);checks.push('CRM export omits passports');
 r=await event({...common,occurred_at:new Date().toISOString(),event_id:'expired',kind:'membership_expired',evidence_ref:'QA-expiry'});assert.equal(r.status,200);r=await event({...common,event_id:'stale-active',kind:'membership_activated'});assert.equal(r.status,200);assert.equal((await call(person1.page,'/me')).body.members[0].entitlement.status,'expired');checks.push('client expiry and stale activation do not revive an ended membership');
 r=await event({...common,event_id:'bad-clinical',kind:'visit',diagnosis:'must reject'});assert.equal(r.status,400);checks.push('clinical fields rejected at integration boundary');
 const evil=await fetch(base+'/api/cprp/auth/options',{method:'POST',headers:{Origin:'https://attacker.invalid','Content-Type':'application/json'},body:JSON.stringify({mode:'login'})});assert.equal(evil.status,403);checks.push('cross-origin mutation rejected');
 const duplicate=await call(person1.page,'/auth/options',{mode:'register',slug:spec.slug,form:{first_name:'Test',last_name:'Test',passport:'QA-A001-'+stamp,phone:'+996000000001'},consent:true});assert.equal(duplicate.status,409);checks.push('duplicate passport cannot create a second entitlement');
 await hr.page.reload();await hr.page.locator('#staff-content').waitFor({state:'visible'});await hr.page.screenshot({path:out+'/hr-desktop.png',fullPage:true});await hr.page.setViewportSize({width:390,height:844});await hr.page.screenshot({path:out+'/hr-mobile.png',fullPage:true});assert.equal(await hr.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);checks.push('HR desktop and mobile render');
 r=await call(hr.page,'/staff/recover',{member_id:member1,identity_rechecked:true});assert.equal(r.status,200);assert.equal((await call(person1.page,'/me')).status,401);const recovered=await device();await recovered.page.goto(r.body.url);await recovered.page.locator('#accept-invite').click();await recovered.page.waitForURL('**/program/member/');assert.equal((await call(recovered.page,'/me')).body.members[0].id,member1);checks.push('HR recovery invalidates old session and preserves participant identity');
 const reused=await call(root.page,'/auth/options',{mode:'register',invite:new URL(r.body.url).hash.split('invite=')[1]});assert.equal(reused.status,403);checks.push('one-time recovery invitation cannot be replayed');
 if(process.env.CPRP_QA_REQUIRE_TWENTY){r=await call(root.page,'/staff/twenty',{action:'configure'});assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.body.verified,true);r=await call(root.page,'/staff/twenty',{action:'sync'});assert.equal(r.status,200);assert.equal(r.body.results.find(x=>x.program_id===program)?.ok,true,JSON.stringify(r));checks.push('live Twenty schema and exact inventory readback verified');}
 for(const id of [program,secondProgram]){r=await call(root.page,'/staff/archive',{program_id:id});assert.equal(r.status,200);}
 if(process.env.CPRP_QA_REQUIRE_TWENTY){r=await call(root.page,'/staff/twenty',{action:'sync'});assert.equal(r.body.results.find(x=>x.program_id===program)?.ok,true);}
 const result={status:'pass',release:health.release,base,checked_at:new Date().toISOString(),synthetic:true,checks,program_id:program};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){fs.writeFileSync(out+'/result.json',JSON.stringify({status:'fail',checks,error:e.message},null,2));console.error(e);process.exitCode=1;}finally{if(root?.page&&!root.page.isClosed())for(const id of [program,secondProgram].filter(Boolean))await call(root.page,'/staff/archive',{program_id:id}).catch(()=>{});await browser.close();}
